### ISSUE TITLE
Error:openDatabase is not defined

### ISSUE THREAD

**Issue by Neznayka17** [crysislinux/smart_websocket_client#10]
Following error appears in console when extension is opened. As a result connect doesn't do anything.
Google Chrome version 119.0.6045.125
```
app.js:1 Uncaught ReferenceError: openDatabase is not defined
    at c.open (app.js:1:12214)
    at e.value (app.js:1:13306)
    at Object.d [as setupDatabase] (common.js:20:6040)
    at n.componentDidMount (app.js:4:14266)
    at r.notifyAll (common.js:1:28147)
    at r.close (common.js:18:26667)
    at r.closeAll (common.js:2:5571)
    at r.perform (common.js:2:4900)
    at g (common.js:3:4087)
    at r.perform (common.js:2:4817)

```

**Comment by crysislinux** [comment]
Hi, thanks for trying the extension. But It has been a long time since the project was published. I don't remember anything about the project now.

There are many other great websocket clients nowadays both as Chrome extensions and standalone apps such as Postman.

Maybe try other apps?
